### ISSUE TITLE
Friendly Remind

### ISSUE THREAD

**Issue by XM-WANG** [ZikangZhou/HiVT#4]

**Comment by XM-WANG** [comment]
I met some errors following the environment configuration.

```
conda install pytorch==1.8.1 cudatoolkit=11.3 -c pytorch -c conda-forge
conda install pytorch-geometric==1.7.2 -c rusty1s -c conda-forge
conda install pytorch-lightning=1.5.2 -c conda-forge
```
will install the torch with CPU version in default.

**Comment by XM-WANG** [comment]
Here is the error:

> (HiVT) bash-4.2$ python train.py --root datasets/ --embed_dim 64
Global seed set to 2022
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    trainer = pl.Trainer.from_argparse_args(args, callbacks=[model_checkpoint])
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1936$
 in from_argparse_args
    return from_argparse_args(cls, args, **kwargs)
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 6$
, in from_argparse_args
    return cls(**trainer_kwargs)
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_co$
nector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 426, 
in __init__
    gpu_ids, tpu_cores = self._parse_devices(gpus, auto_select_gpus, tpu_cores)
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1538$
 in _parse_devices
    gpu_ids = device_parser.parse_gpu_ids(gpus)
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", l$
ne 89, in parse_gpu_ids
    return _sanitize_gpu_ids(gpus)
  File "/misc/kfdata01/kf_grp/zzwang/anaconda3/envs/HiVT/lib/python3.8/site-packages/pytorch_lightning/utilities/device_parser.py", l$
ne 151, in _sanitize_gpu_ids
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: You requested GPUs: [0]
 But your machine only has: []

**Comment by XM-WANG** [comment]
![image](https://user-images.githubusercontent.com/43406982/175805570-0a01e1ea-46a5-4a09-b0bb-6108af50ae16.png)
It is because the torch cannot find the GPU device. I re-installed torch and fix this error.

**Comment by ZikangZhou** [comment]
Thanks a lot! It seems that cuda-version Pytorch 1.8.1 cannot be downloaded correctly. Pytorch 1.8.0 seems to work well.
